Cprbucat2/issue2
cprbucat2/team-feedback pull request #34
Opened 2023-06-20 20:54 UTC by cprbucat2

[Feature] Added all elements of example form.

## Old behavior
Old HTML form only had the class title.

## New behavior
HTML form has all sections of the example, it is static and using text boxes.

2023-06-22 03:30 UTC, bobpaw requested changes

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +			<tr class="ratings-table-colavg">
This row should be centered (and gray background). Actually looks like you just have a typo in the class name:
```suggestion
			<tr class="ratings-table__colavg">
```

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +			<tr>
Add a BEM class to this row so we can easily change the number of team members.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +			  <th>Participation</th>
Add a class to each column header so we can easily add any number of categories. The team member class should be distinct from the categories.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +    <div>
Add a BEM class like "course description" or something so we can easily edit this.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +    <div class="text-center text-bold">
Make this class like section title or something so we can easily add any number of sections. Also enclose both this and the description and the table below in a div with a class like feedback section or something.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +    <div>
Definitely make this a section description class

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +	<div class="text-center text-bold">
Enclose this section title and the next flex-container in a div.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +		  <div class="col1 text-bold">Participation<br>Collaboration<br>Contribution<br>Attitude<br>Goals</div>
It makes more sense to have many rows with no top/bottom border in case the category name or category description text needs two lines. Also add a BEM class for these.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +				<div><textarea class="textarea2 text-bold" id="self_comments" rows="4" cols="20">Enter comments for yourself here...</textarea></div>
The textarea is bold in the spec but maybe... shouldn't be? it was probably bold by default because the "comments (self)" part is in bold.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +				<div class="text-underline text-bold">Comments (self): </div>
Let's use the contentEditable attribute here to match the spec as close as possible. See https://stackoverflow.com/a/5444929/3413725 (or google it) for examples

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +	<table>
We could instead use a div with `display: table` and an appropriate BEM class.

2023-06-22 03:30 UTC, bobpaw commented on app/www/index.html
> +			<td>
Definitely add a BEM class to this so we can have a variable number of group members.

2023-06-22 03:30 UTC, bobpaw commented on app/www/styles.css
> +section {
Please use BEM classes instead of explicit tag names in CSS.

2023-06-22 03:30 UTC, bobpaw commented on app/www/styles.css
> +section > * {
Please use BEM classes instead of the direct child `>` selector. Also the `*` selector feels very dangerous.

2023-06-23 18:39 UTC, bobpaw commented on app/www/index.html
> +				<div class="text-underline text-bold">Comments (self): </div>
Looks like this can't be done with a standard `<textarea>` element and doing it with a `<div contenteditable="true">` introduces data loss issues. Marking as resolved.

2023-06-27 18:27 UTC, bobpaw approved these changes
Looks good. Switch to tables instead of flexboxes is fine probably. Looks weird on mobile but I opened #44 to address that.

2023-06-27 18:33 UTC, cprbucat2 commented on app/www/index.html
> +				<div><textarea class="textarea2 text-bold" id="self_comments" rows="4" cols="20">Enter comments for yourself here...</textarea></div>
On the example the words look more bold than the non bold, this is good because it is important to be filled out.

2023-06-27 19:08 UTC, bobpaw commented on app/www/index.html
> +		  <div class="col1 text-bold">Participation<br>Collaboration<br>Contribution<br>Attitude<br>Goals</div>
Split into multiple rows in [8817362](https://github.com/cprbucat2/team-feedback/pull/34/commits/8817362a64e03c0369eb4dab80bffab9c437450b).

2023-06-27 19:24 UTC, merged